//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace At.luki0606.ClassPulse.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("At.luki0606.ClassPulse.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add exam for the selected subject:.
        /// </summary>
        public static string Dialog_NewAssessment_Message {
            get {
                return ResourceManager.GetString("Dialog_NewAssessment_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new exam.
        /// </summary>
        public static string Dialog_NewAssessment_Title {
            get {
                return ResourceManager.GetString("Dialog_NewAssessment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the details for the new class:.
        /// </summary>
        public static string Dialog_NewClass_Message {
            get {
                return ResourceManager.GetString("Dialog_NewClass_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New School Class.
        /// </summary>
        public static string Dialog_NewClass_Title {
            get {
                return ResourceManager.GetString("Dialog_NewClass_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Pupil.
        /// </summary>
        public static string Dialog_NewPupil_Message {
            get {
                return ResourceManager.GetString("Dialog_NewPupil_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name of Pupil:.
        /// </summary>
        public static string Dialog_NewPupil_Title {
            get {
                return ResourceManager.GetString("Dialog_NewPupil_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter data in order to create a new subject:.
        /// </summary>
        public static string Dialog_NewSubject_Message {
            get {
                return ResourceManager.GetString("Dialog_NewSubject_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Dialog_NewSubject_Title {
            get {
                return ResourceManager.GetString("Dialog_NewSubject_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a subject:.
        /// </summary>
        public static string Dialog_SelectSubject_Message {
            get {
                return ResourceManager.GetString("Dialog_SelectSubject_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occured:.
        /// </summary>
        public static string General_ExceptionHasOccured {
            get {
                return ResourceManager.GetString("General_ExceptionHasOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new class.
        /// </summary>
        public static string Home_AddClassTooltip {
            get {
                return ResourceManager.GetString("Home_AddClassTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Class.
        /// </summary>
        public static string Home_BtnGoToClass {
            get {
                return ResourceManager.GetString("Home_BtnGoToClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected class.
        /// </summary>
        public static string Home_DeleteClassTooltip {
            get {
                return ResourceManager.GetString("Home_DeleteClassTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select School Class.
        /// </summary>
        public static string Home_SelectClassLabel {
            get {
                return ResourceManager.GetString("Home_SelectClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a class....
        /// </summary>
        public static string Home_SelectClassPlaceholder {
            get {
                return ResourceManager.GetString("Home_SelectClassPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string Label_Average {
            get {
                return ResourceManager.GetString("Label_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Label_Cancel {
            get {
                return ResourceManager.GetString("Label_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name.
        /// </summary>
        public static string Label_ClassName {
            get {
                return ResourceManager.GetString("Label_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Label_FirstName {
            get {
                return ResourceManager.GetString("Label_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g..
        /// </summary>
        public static string Label_for_example_abbr {
            get {
                return ResourceManager.GetString("Label_for_example_abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Label_Home {
            get {
                return ResourceManager.GetString("Label_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Label_LastName {
            get {
                return ResourceManager.GetString("Label_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mathematics.
        /// </summary>
        public static string Label_Mathematics {
            get {
                return ResourceManager.GetString("Label_Mathematics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pupil.
        /// </summary>
        public static string Label_Pupil {
            get {
                return ResourceManager.GetString("Label_Pupil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Label_Save {
            get {
                return ResourceManager.GetString("Label_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Year.
        /// </summary>
        public static string Label_SchoolYear {
            get {
                return ResourceManager.GetString("Label_SchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name.
        /// </summary>
        public static string Label_ShortName {
            get {
                return ResourceManager.GetString("Label_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Label_Subject {
            get {
                return ResourceManager.GetString("Label_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Name.
        /// </summary>
        public static string Label_SubjectName {
            get {
                return ResourceManager.GetString("Label_SubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Label_Test {
            get {
                return ResourceManager.GetString("Label_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        public static string Label_Titel {
            get {
                return ResourceManager.GetString("Label_Titel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weighting.
        /// </summary>
        public static string Label_Weight {
            get {
                return ResourceManager.GetString("Label_Weight", resourceCulture);
            }
        }
    }
}
